const HOUSES_PER_PAGE = 12;
const MAX_RETRIES = 7;
const OBSERVER_THRESHOLD = 0.5;
const NAVBAR_TITLE = "Houses Feed";
const FILTER_BUTTON_LABEL = "Filter";
const MAXPRICE_CHIP_LABEL = "Max Price: $";
const MAXPRICE_MINVALUE = 80000;
const MAXPRICE_MAXVALUE = 350000;
const MAXPRICE_MODAL_LABEL = "Max Price";
const APPLY_MODAL_LABEL = "Apply";
const CANCEL_MODAL_LABEL = "Cancel";
const SHARE_BUTTON_LABEL = "Share";
const CONTACT_BUTTON_LABEL = "Contact";
const NOHOUSES_TEXT = "That's all for now! Check back soon for more houses.";
const NORETRIES_TEXT =
  "Oops! We're having some trouble. Please try reloading in a moment.";
export {
  HOUSES_PER_PAGE,
  NAVBAR_TITLE,
  FILTER_BUTTON_LABEL,
  MAXPRICE_CHIP_LABEL,
  MAXPRICE_MINVALUE,
  MAXPRICE_MAXVALUE,
  MAXPRICE_MODAL_LABEL,
  APPLY_MODAL_LABEL,
  CANCEL_MODAL_LABEL,
  SHARE_BUTTON_LABEL,
  CONTACT_BUTTON_LABEL,
  NOHOUSES_TEXT,
  NORETRIES_TEXT,
  MAX_RETRIES,
  OBSERVER_THRESHOLD,
};
